### ISSUE TITLE
NAA的结果

### ISSUE THREAD

**Issue by zepengF** [RYC-98/SFVA#1]
NAA的结果是否存在问题，参数设置是如何设置的？NAA文章中结果是要比FIA好的。
下面是在incv3模型上的部分结果
![image](https://github.com/RYC-98/SFVA/assets/48851922/b5534fa0-bd71-4bb1-8c0a-da9a42264411)

![image](https://github.com/RYC-98/SFVA/assets/48851922/7f49fc09-6d42-45bd-8914-d095440b6d4c)

**Comment by RYC-98** [comment]
NAA 的官方代码中多了一行加高斯噪声的操作，但NAA论文中没有提到这一操作。因此我把那一行代码去掉了，最终效果不如FIA


| |
ryc_981015
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年9月18日 16:18 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [RYC-98/SFVA] NAA的结果 (Issue #1) |

NAA的结果是否存在问题，参数设置是如何设置的？NAA文章中结果是要比FIA好的。
下面是在incv3模型上的部分结果

**Comment by wanqiang512** [comment]
> NAA 的官方代码中多了一行加高斯噪声的操作，但NAA论文中没有提到这一操作。因此我把那一行代码去掉了，最终效果不如FIA | | ryc_981015 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年9月18日 16:18 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | [RYC-98/SFVA] NAA的结果 (Issue #1) | NAA的结果是否存在问题，参数设置是如何设置的？NAA文章中结果是要比FIA好的。 下面是在incv3模型上的部分结果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

高斯噪声是对图像达到一个去噪的效果，基于SmoothGrad，论文中有简短的提到过

**Comment by wanqiang512** [comment]
> NAA 的官方代码中多了一行加高斯噪声的操作，但NAA论文中没有提到这一操作。因此我把那一行代码去掉了，最终效果不如FIA | | ryc_981015 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年9月18日 16:18 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> | | 主题 | [RYC-98/SFVA] NAA的结果 (Issue #1) | NAA的结果是否存在问题，参数设置是如何设置的？NAA文章中结果是要比FIA好的。 下面是在incv3模型上的部分结果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

高斯噪声是对图像达到一种去噪的效果，基于SmoothGrad，NAA论文简短的提到过
